version: "3"
services:
  vote:
    build: .
    container_name: vote
    depends_on:
      - mongodb
    environment:
      VOTE_HOST: 'http://localhost:8080'
      VOTE_JWT_SECRET: 4874c601dda90a01c7543c571be08680
      VOTE_MONGODB_URI: "mongodb://vote:c1f66aac6b4fafbef3c659371b8a50ed@mongodb/vote?authSource=admin"
      VOTE_OIDC_ID: vote
      VOTE_OIDC_SECRET: "${VOTE_OIDC_SECRET}"
      VOTE_STATE: 27a28540e47ec786b7bdad03f83171b3
    ports:
      - "127.0.0.1:8080:8080"

  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    command: "mongod --bind_ip 0.0.0.0"
    environment:
      - "MONGO_INITDB_DATABASE=vote"
      - "MONGO_INITDB_ROOT_USERNAME=vote"
      - "MONGO_INITDB_ROOT_PASSWORD=c1f66aac6b4fafbef3c659371b8a50ed"
    volumes:
      - type: volume
        source: mongo
        target: /data/db/

volumes:
  mongo:
